# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new-entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(496, 307)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 80, 57, 15))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setGeometry(QtCore.QRect(160, 250, 121, 31))
        self.create_button.setObjectName("create_button")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 151, 16))
        self.label_4.setObjectName("label_4")
        self.title_input = QtWidgets.QLineEdit(Dialog)
        self.title_input.setGeometry(QtCore.QRect(182, 70, 211, 23))
        self.title_input.setObjectName("title_input")
        self.login_input = QtWidgets.QLineEdit(Dialog)
        self.login_input.setGeometry(QtCore.QRect(180, 120, 211, 23))
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(Dialog)
        self.password_input.setGeometry(QtCore.QRect(180, 160, 211, 23))
        self.password_input.setObjectName("password_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add New Entry"))
        self.label.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "Login"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.create_button.setText(_translate("Dialog", "Create"))
        self.label_4.setText(_translate("Dialog", "Add a new entry"))
